# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1df52932fce3b08b960ab66ca4ccd8c9"
name = "Wholesale Engine AI"
application_url = "https://wholesale.webvory.com"
embedded = true
handle = "ai-wholesale-engine"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/update"
  topics = [ "customers/create", "customers/update" ]

   [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]


[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_discounts,read_markets,read_metaobject_definitions,read_metaobjects,read_orders,read_price_rules,read_products,read_script_tags,read_shipping,write_customers,write_discounts,write_markets,write_metaobject_definitions,write_metaobjects,write_price_rules,write_products,write_script_tags,write_shipping,write_online_store_navigation "
optional_scopes = [ ]

[auth]
redirect_urls = [
  "https://wholesale.webvory.com/api/auth/callback"
]

[product.metafields.app.demo_info]
type = "single_line_text_field"
name = "Demo Source Info"
description = "Tracks products created by the Shopify app template for development"

  [product.metafields.app.demo_info.access]
  admin = "merchant_read_write"

[metaobjects.app.example]
name = "Example"
description = "An example metaobject definition created by this template"

  [metaobjects.app.example.access]
  admin = "merchant_read_write"

[metaobjects.app.example.fields.title]
name = "Title"
type = "single_line_text_field"
required = true

[metaobjects.app.example.fields.description]
name = "Description"
type = "multi_line_text_field"

[app_proxy]
url = "https://wholesale.webvory.com/api/proxy"
subpath = "wholesale"
prefix = "apps"
