api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "cart-quantity-validation"
type = "function"
uid = "2ed61549-af76-bb2c-71d3-50e24c3f3f22b6dbf0d0"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
