name: Build, Push and Deploy Wholesale App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-west-1 | \
          docker login --username AWS --password-stdin \
          450367038243.dkr.ecr.us-west-1.amazonaws.com

      - name: Build Image
        run: |
          docker build -t shopify-wholesale-app .

      - name: Tag Image
        run: |
          docker tag shopify-wholesale-app:latest \
          450367038243.dkr.ecr.us-west-1.amazonaws.com/shopify-wholesale-app:latest

          docker tag shopify-wholesale-app:latest \
          450367038243.dkr.ecr.us-west-1.amazonaws.com/shopify-wholesale-app:${{ github.sha }}

      - name: Push Image
        run: |
          docker push 450367038243.dkr.ecr.us-west-1.amazonaws.com/shopify-wholesale-app:latest
          docker push 450367038243.dkr.ecr.us-west-1.amazonaws.com/shopify-wholesale-app:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            set -xeov

            aws ecr get-login-password --region us-west-1 | \
            docker login --username AWS --password-stdin \
                450367038243.dkr.ecr.us-west-1.amazonaws.com

            docker pull 450367038243.dkr.ecr.us-west-1.amazonaws.com/shopify-wholesale-app:latest

